provider:
  name: aws
  runtime: python3.9
  profile: my-aws-profile
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::login-data-bucket/*

  custom:
    stage: ${opt:stage, self:provider.stage}
    credentials: ${file(credentials.yml)}

    pythonRequirements:
      dockerizePip: non-linux
      slim: true

  functions:
    signup:
      handler: wsgi.handler
      events:
        - http:
            path: /
            method: any
            cors: true

  plugins:
    - serverless-wsgi
    - serverless-python-requirements